# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: conn-mgr-lib
      url-base: https://github.com/Naquino14/conn-mgr

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: v4.4.2
      import:
        path-prefix: deps
    - name: conn-mgr
      revision: master
      remote: conn-mgr-lib
      path: modules/lib/conn-mgr

  self:
    path: hot-or-not
