# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: conn-mgr
      url-base: https://github.com/Naquino14

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: v4.4.2
      import:
        name-allowlist:
          - hal_espressif
          - mbedtls
          - tf-psa-crypto
      clone-depth: 1
    - name: conn-mgr
      repo-path: conn-mgr
      remote: conn-mgr
      revision: master

  self:
    path: hot-or-not
