# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: v4.4.2
      import:
        path-prefix: deps
        name-allowlist:
          - hal_espressif
          - mbedtls
      clone-depth: 1

  self:
    path: hot-or-not
