# RENAMEME -> secrets.conf

CONFIG_WIFI_SSID="MySSID"
CONFIG_WIFI_SECURITY=1
CONFIG_WIFI_PSK="MyPassword"
CONFIG_SMTP_SECRET="MyAppPassword"
CONFIG_SMTP_EMAIL="foo@bar.com"
CONFIG_SMTP_SERVER="smtp.example.com"